export enum actionTypes {
  FETCH_DATA = "FETCH_DATA",
  FETCH_ARCHIVE = "FECTH_ARCHIVE",
  PATCH_NOTE = "PATCH_NOTE",
  ADD_NOTE = "ADD_NOTE",
  SET_ACTIVE_NOTES = "SET_ACTIVE_NOTES",
  SET_ARCHIVE_NOTES = "SET_ARCHIVE_NOTES",
  CHECK_ITEM = "CHECK_ITEM",
  FILTER_ITEMS = "FILTER_ITEMS",
  SEARCH_ITEMS = "SEARCH_ITEMS",
  ARCHIVE_ITEM = "ARCHIVE_ITEM"
}
