export enum actionTypes {
  FETCH_DATA = "FETCH_DATA",
  FETCH_NOTES = "FETCH_NOTES",
  FETCH_ARCHIVE = "FECTH_ARCHIVE",
  SET_ACTIVE_NOTES = "SET_ACTIVE_NOTES",
  SET_ARCHIVE_NOTES = "SET_ARCHIVE_NOTES"
}
